#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class DetallePedido
	{
		private int idDetallePedido;
		public virtual int IdDetallePedido
		{
			get
			{
				return this.idDetallePedido;
			}
			set
			{
				this.idDetallePedido = value;
			}
		}
		
		private int idPedido;
		public virtual int IdPedido
		{
			get
			{
				return this.idPedido;
			}
			set
			{
				this.idPedido = value;
			}
		}
		
		private string codigoProducto;
		public virtual string CodigoProducto
		{
			get
			{
				return this.codigoProducto;
			}
			set
			{
				this.codigoProducto = value;
			}
		}
		
		private int? cantidad;
		public virtual int? Cantidad
		{
			get
			{
				return this.cantidad;
			}
			set
			{
				this.cantidad = value;
			}
		}
		
		private decimal? precio;
		public virtual decimal? Precio
		{
			get
			{
				return this.precio;
			}
			set
			{
				this.precio = value;
			}
		}
		
		private string nombreProducto;
		public virtual string NombreProducto
		{
			get
			{
				return this.nombreProducto;
			}
			set
			{
				this.nombreProducto = value;
			}
		}
		
		private Pedido pedido;
		public virtual Pedido Pedido
		{
			get
			{
				return this.pedido;
			}
			set
			{
				this.pedido = value;
			}
		}
		
	}
}
#pragma warning restore 1591
