#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class DetallePedidoTemporal
	{
		private int idDetallePedidoTemporal;
		public virtual int IdDetallePedidoTemporal
		{
			get
			{
				return this.idDetallePedidoTemporal;
			}
			set
			{
				this.idDetallePedidoTemporal = value;
			}
		}
		
		private int? idProducto;
		public virtual int? IdProducto
		{
			get
			{
				return this.idProducto;
			}
			set
			{
				this.idProducto = value;
			}
		}
		
		private int? cantidad;
		public virtual int? Cantidad
		{
			get
			{
				return this.cantidad;
			}
			set
			{
				this.cantidad = value;
			}
		}
		
		private decimal? precio;
		public virtual decimal? Precio
		{
			get
			{
				return this.precio;
			}
			set
			{
				this.precio = value;
			}
		}
		
		private int? idUsuario;
		public virtual int? IdUsuario
		{
			get
			{
				return this.idUsuario;
			}
			set
			{
				this.idUsuario = value;
			}
		}
		
		private Producto producto;
		public virtual Producto Producto
		{
			get
			{
				return this.producto;
			}
			set
			{
				this.producto = value;
			}
		}
		
		private Usuario usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this.usuario;
			}
			set
			{
				this.usuario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
