#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Pedido
	{
		private int idPedido;
		public virtual int IdPedido
		{
			get
			{
				return this.idPedido;
			}
			set
			{
				this.idPedido = value;
			}
		}
		
		private int? idUsuario;
		public virtual int? IdUsuario
		{
			get
			{
				return this.idUsuario;
			}
			set
			{
				this.idUsuario = value;
			}
		}
		
		private string pedidoMes;
		public virtual string PedidoMes
		{
			get
			{
				return this.pedidoMes;
			}
			set
			{
				this.pedidoMes = value;
			}
		}
		
		private int? pedidoDia;
		public virtual int? PedidoDia
		{
			get
			{
				return this.pedidoDia;
			}
			set
			{
				this.pedidoDia = value;
			}
		}
		
		private int? pedidoAnio;
		public virtual int? PedidoAnio
		{
			get
			{
				return this.pedidoAnio;
			}
			set
			{
				this.pedidoAnio = value;
			}
		}
		
		private string numeroPedido;
		public virtual string NumeroPedido
		{
			get
			{
				return this.numeroPedido;
			}
			set
			{
				this.numeroPedido = value;
			}
		}
		
		private Usuario usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this.usuario;
			}
			set
			{
				this.usuario = value;
			}
		}
		
		private IList<DetallePedido> detallePedidos = new List<DetallePedido>();
		public virtual IList<DetallePedido> DetallePedidos
		{
			get
			{
				return this.detallePedidos;
			}
		}
		
	}
}
#pragma warning restore 1591
