#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class PresupuestoTemporal
	{
		private int idPresupuestoTemporal;
		public virtual int IdPresupuestoTemporal
		{
			get
			{
				return this.idPresupuestoTemporal;
			}
			set
			{
				this.idPresupuestoTemporal = value;
			}
		}
		
		private string codigoProducto;
		public virtual string CodigoProducto
		{
			get
			{
				return this.codigoProducto;
			}
			set
			{
				this.codigoProducto = value;
			}
		}
		
		private int? cantidad;
		public virtual int? Cantidad
		{
			get
			{
				return this.cantidad;
			}
			set
			{
				this.cantidad = value;
			}
		}
		
		private decimal? precio;
		public virtual decimal? Precio
		{
			get
			{
				return this.precio;
			}
			set
			{
				this.precio = value;
			}
		}
		
		private int? idUsuario;
		public virtual int? IdUsuario
		{
			get
			{
				return this.idUsuario;
			}
			set
			{
				this.idUsuario = value;
			}
		}
		
		private string nombreProducto;
		public virtual string NombreProducto
		{
			get
			{
				return this.nombreProducto;
			}
			set
			{
				this.nombreProducto = value;
			}
		}
		
		private Usuario usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this.usuario;
			}
			set
			{
				this.usuario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
