#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Producto
	{
		private int idProducto;
		public virtual int IdProducto
		{
			get
			{
				return this.idProducto;
			}
			set
			{
				this.idProducto = value;
			}
		}
		
		private string codigo;
		public virtual string Codigo
		{
			get
			{
				return this.codigo;
			}
			set
			{
				this.codigo = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private decimal? precio;
		public virtual decimal? Precio
		{
			get
			{
				return this.precio;
			}
			set
			{
				this.precio = value;
			}
		}
		
		private int? stock;
		public virtual int? Stock
		{
			get
			{
				return this.stock;
			}
			set
			{
				this.stock = value;
			}
		}
		
		private IList<DetallePedido> detallePedidos = new List<DetallePedido>();
		public virtual IList<DetallePedido> DetallePedidos
		{
			get
			{
				return this.detallePedidos;
			}
		}
		
		private IList<DetallePedidoTemporal> detallePedidoTemporals = new List<DetallePedidoTemporal>();
		public virtual IList<DetallePedidoTemporal> DetallePedidoTemporals
		{
			get
			{
				return this.detallePedidoTemporals;
			}
		}
		
	}
}
#pragma warning restore 1591
